# Pin npm packages by running ./bin/importmap

pin "application"
pin "@hotwired/turbo-rails", to: "turbo.min.js"
pin "@hotwired/stimulus", to: "stimulus.min.js"
pin "@hotwired/stimulus-loading", to: "stimulus-loading.js"
pin_all_from "app/javascript/controllers", under: "controllers"
pin "highlight.js", to: "https://ga.jspm.io/npm:highlight.js@11.9.0/es/index.js"

# CodeMirror 6
pin "codemirror", to: "https://cdn.jsdelivr.net/npm/codemirror@6.0.1/dist/index.js"
pin "@codemirror/autocomplete", to: "https://cdn.jsdelivr.net/npm/@codemirror/autocomplete@6.12.0/dist/index.js"
pin "@codemirror/commands", to: "https://cdn.jsdelivr.net/npm/@codemirror/commands@6.3.3/dist/index.js"
pin "@codemirror/language", to: "https://cdn.jsdelivr.net/npm/@codemirror/language@6.10.0/dist/index.js"
pin "@codemirror/lint", to: "https://cdn.jsdelivr.net/npm/@codemirror/lint@6.4.2/dist/index.js"
pin "@codemirror/search", to: "https://cdn.jsdelivr.net/npm/@codemirror/search@6.5.5/dist/index.js"
pin "@codemirror/state", to: "https://cdn.jsdelivr.net/npm/@codemirror/state@6.4.0/dist/index.js"
pin "@codemirror/view", to: "https://cdn.jsdelivr.net/npm/@codemirror/view@6.23.0/dist/index.js"
pin "@codemirror/legacy-modes/mode/ruby", to: "https://cdn.jsdelivr.net/npm/@codemirror/legacy-modes@6.4.0/mode/ruby.js"
pin "@codemirror/theme-one-dark", to: "https://cdn.jsdelivr.net/npm/@codemirror/theme-one-dark@6.1.2/dist/index.js"
pin "@lezer/common", to: "https://cdn.jsdelivr.net/npm/@lezer/common@1.2.1/dist/index.js"
pin "@lezer/highlight", to: "https://cdn.jsdelivr.net/npm/@lezer/highlight@1.2.0/dist/index.js"
pin "@lezer/lr", to: "https://cdn.jsdelivr.net/npm/@lezer/lr@1.4.0/dist/index.js"
pin "crelt", to: "https://cdn.jsdelivr.net/npm/crelt@1.0.6/index.js"
pin "style-mod", to: "https://cdn.jsdelivr.net/npm/style-mod@4.1.0/src/style-mod.js"
pin "w3c-keyname", to: "https://cdn.jsdelivr.net/npm/w3c-keyname@2.2.8/index.js"
